// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-designs/BitcoinNoir.tsx": () => import("../components/mockups/hero-designs/BitcoinNoir.tsx"),
  "./components/mockups/hero-designs/CyberGrid.tsx": () => import("../components/mockups/hero-designs/CyberGrid.tsx"),
  "./components/mockups/hero-designs/DarkGlass.tsx": () => import("../components/mockups/hero-designs/DarkGlass.tsx")
};
