import { pgTable, text, serial, integer, decimal, timestamp, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// =====================================================
// DETERMINISTIC OUTCOME ENGINE
// =====================================================

// Loan outcome types for deterministic dispute resolution
export const LoanOutcomeEnum = z.enum([
  'COOPERATIVE_CLOSE',  // Normal repayment - borrower paid, return collateral
  'DEFAULT',            // Borrower failed to pay - collateral to lender
  'LIQUIDATION',        // Price dropped below threshold - liquidate collateral
  'CANCELLATION',       // Lender never funded - cancel and return
  'RECOVERY',           // Platform recovery - emergency fund return
  'UNDER_REVIEW',       // Insufficient evidence to decide
]);

export type LoanOutcome = z.infer<typeof LoanOutcomeEnum>;

// Evidence structure for outcome decision
export const DisputeEvidenceSchema = z.object({
  lenderFunded: z.boolean(),
  lenderConfirmedPaid: z.boolean(),
  borrowerConfirmedReceipt: z.boolean(),
  currentBtcPriceUsd: z.number(),
  liquidationThresholdUsd: z.number(),
  collateralBtc: z.number(),
  dueDate: z.date().nullable(),
  loanStatus: z.string(),
  escrowState: z.string().nullable(),
});

export type DisputeEvidence = z.infer<typeof DisputeEvidenceSchema>;

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  role: text("role").notNull().default("user"), // user (can both borrow and lend)
  reputation: integer("reputation").notNull().default(0),
  completedLoans: integer("completed_loans").notNull().default(0),
  emailVerified: boolean("email_verified").notNull().default(false),
  emailVerificationToken: text("email_verification_token"),
  emailVerificationExpires: timestamp("email_verification_expires"),
  passwordResetToken: text("password_reset_token"),
  passwordResetExpires: timestamp("password_reset_expires"),
  
  // Personal Details
  firstName: text("first_name"),
  lastName: text("last_name"),
  phonePrefix: text("phone_prefix"), // e.g., "+34", "+1"
  phoneNumber: text("phone_number"),
  
  // Bank Account Details (for receiving loan funds)
  bankAccountHolder: text("bank_account_holder"),
  bankAccountNumber: text("bank_account_number"),
  bankName: text("bank_name"),
  bankRoutingNumber: text("bank_routing_number"), // For US banks
  iban: text("iban"), // For European banks
  bankCountry: text("bank_country"),
  
  // Bitcoin Address (for recovery, returns, etc.)
  btcAddress: text("btc_address"),
  
  // Pending Personal Details Changes (requires email confirmation)
  pendingDetailsChange: text("pending_details_change"), // JSON blob with pending changes
  detailsChangeToken: text("details_change_token"),
  detailsChangeExpires: timestamp("details_change_expires"),
  
  // Admin OTP Authentication (email-based one-time codes)
  adminOtpCode: text("admin_otp_code"), // 6-digit code
  adminOtpExpires: timestamp("admin_otp_expires"), // Code expiry time (5 minutes)
  
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const loans = pgTable("loans", {
  id: serial("id").primaryKey(),
  borrowerId: integer("borrower_id").notNull(),
  lenderId: integer("lender_id"),
  amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),
  currency: text("currency").notNull().default("USDC"),
  interestRate: decimal("interest_rate", { precision: 5, scale: 2 }).notNull(),
  termMonths: integer("term_months").notNull(),
  collateralBtc: decimal("collateral_btc", { precision: 10, scale: 8 }).notNull(),
  ltvRatio: decimal("ltv_ratio", { precision: 5, scale: 2 }).notNull(),
  purpose: text("purpose"),
  status: text("status").notNull().default("posted"), // posted, matched, borrower_keys_submitted, funding, active, completed, defaulted
  requestedAt: timestamp("requested_at").notNull().defaultNow(),
  fundedAt: timestamp("funded_at"),
  dueDate: timestamp("due_date"),
  repaidAt: timestamp("repaid_at"),
  plannedStartDate: timestamp("planned_start_date"), // Fixed at lender commitment (today + 7 days)
  plannedEndDate: timestamp("planned_end_date"), // Fixed at lender commitment (start + term)
  
  // WASM-Generated Escrow Fields (NO PRIVATE KEYS!)
  escrowAddress: text("escrow_address"), // Generated by WASM in browser
  escrowWitnessScript: text("escrow_witness_script"), // P2WSH witness script
  escrowScriptHash: text("escrow_script_hash"),
  
  // 3-of-3 Multisig Public Keys (Bitcoin-blind lender design)
  // NOTE: Lenders are Bitcoin-blind - the "lenderPubkey" is actually PLATFORM-GENERATED
  // - borrowerPubkey: Client-generated, borrower controls
  // - lenderPubkey: Platform-generated key for lender's escrow position (lender never sees this!)
  // - platformPubkey: Platform's own signing key
  borrowerPubkey: text("borrower_pubkey"),
  lenderPubkey: text("lender_pubkey"), // Platform-operated key (lender is Bitcoin-blind)
  platformPubkey: text("platform_pubkey"),
  
  // Encrypted lender key private key (platform signs on behalf of lender after fiat confirmation)
  lenderPrivateKeyEncrypted: text("lender_private_key_encrypted"),
  
  // Blockchain Transaction Tracking
  fundingTxid: text("funding_txid"), // Funding transaction ID
  fundingVout: integer("funding_vout"), // Output index
  fundedAmountSats: integer("funded_amount_sats"),
  
  // Escrow Workflow State
  escrowState: text("escrow_state").default("initialized"), // initialized, escrow_created, deposit_confirmed, keys_generated, active, completed, defaulted
  escrowSessionId: text("escrow_session_id"), // Links to escrow_sessions table
  
  // Workflow Flags
  fiatTransferConfirmed: boolean("fiat_transfer_confirmed").default(false),
  borrowerConfirmedReceipt: boolean("borrower_confirmed_receipt").default(false),
  btcDepositNotifiedAt: timestamp("btc_deposit_notified_at"), // When borrower clicked "I've Sent BTC"
  depositConfirmedAt: timestamp("deposit_confirmed_at"), // When blockchain confirms BTC in escrow
  
  // Automated Deposit Monitoring
  depositTxid: text("deposit_txid"), // Transaction ID provided by borrower (optional)
  depositConfirmations: integer("deposit_confirmations").default(0), // Current blockchain confirmations
  escrowMonitoringActive: boolean("escrow_monitoring_active").default(false), // Whether we're actively polling
  lastMonitorCheckAt: timestamp("last_monitor_check_at"), // Last time we checked blockchain
  borrowerKeysGeneratedAt: timestamp("borrower_keys_generated_at"), // When borrower generated ephemeral keys
  lenderKeysGeneratedAt: timestamp("lender_keys_generated_at"), // When lender generated ephemeral keys
  loanStartedAt: timestamp("loan_started_at"),
  
  // Repayment Confirmation
  repaymentConfirmedByBorrower: boolean("repayment_confirmed_by_borrower").default(false),
  repaymentConfirmedAt: timestamp("repayment_confirmed_at"),
  
  // Dispute Resolution (Platform Intermediary)
  disputeStatus: text("dispute_status").default("none"), // none, under_review, resolved
  disputeResolvedAt: timestamp("dispute_resolved_at"),
  
  // Pre-signed Transaction Hex Storage (for disputes)
  txRepaymentHex: text("tx_repayment_hex"), // Cooperative close transaction hex
  txDefaultHex: text("tx_default_hex"), // Default (borrower non-payment) transaction hex
  txLiquidationHex: text("tx_liquidation_hex"), // Post-maturity liquidation transaction hex
  txRecoveryHex: text("tx_recovery_hex"), // Platform recovery transaction hex
  txCancellationHex: text("tx_cancellation_hex"), // Lender-initiated cancellation transaction hex
  
  // Signing Ceremony Status
  borrowerSigningComplete: boolean("borrower_signing_complete").default(false), // Borrower completed signing ceremony
  
  // Borrower Return Address (where collateral is returned after successful repayment)
  borrowerAddress: text("borrower_address"), // tb1q... or bc1q... bech32 address
  
  // Partial Deposit Warning
  partialDepositWarningAt: timestamp("partial_deposit_warning_at"), // When we sent insufficient deposit warning email
  partialDepositAmountSats: integer("partial_deposit_amount_sats"), // Amount detected that was insufficient
  
  // Collateral Top-Up Tracking
  pendingTopUpBtc: decimal("pending_top_up_btc", { precision: 10, scale: 8 }), // Amount borrower claims to have sent
  topUpRequestedAt: timestamp("top_up_requested_at"), // When borrower clicked "I've topped up"
  topUpConfirmedAt: timestamp("top_up_confirmed_at"), // When blockchain confirmed the top-up
  topUpMonitoringActive: boolean("top_up_monitoring_active").default(false), // Whether actively monitoring for top-up
  previousCollateralBtc: decimal("previous_collateral_btc", { precision: 10, scale: 8 }), // Collateral before top-up (for verification)
  topUpDetectedInMempoolAt: timestamp("top_up_detected_in_mempool_at"), // When we first saw the top-up in mempool
  topUpTxid: text("top_up_txid"), // Transaction ID of the top-up deposit
  
  // Dispute Resolution - Lender Signature Flow
  pendingResolutionPsbt: text("pending_resolution_psbt"), // Base64 PSBT awaiting lender signature
  pendingResolutionDecision: text("pending_resolution_decision"), // LENDER_WINS, BORROWER_WINS, etc.
  pendingResolutionLenderSats: integer("pending_resolution_lender_sats"), // Lender's payout in sats
  pendingResolutionBorrowerSats: integer("pending_resolution_borrower_sats"), // Borrower's payout in sats
  pendingResolutionBtcPrice: decimal("pending_resolution_btc_price", { precision: 12, scale: 2 }), // BTC/EUR price used
  pendingResolutionCreatedAt: timestamp("pending_resolution_created_at"), // When admin created the resolution
  lenderSignatureHex: text("lender_signature_hex"), // Lender's signature once provided
  lenderSignedAt: timestamp("lender_signed_at"), // When lender signed
  
  // Collateral Release Tracking
  collateralReleaseTxid: text("collateral_release_txid"), // TXID when collateral returned to borrower
  collateralReleasedAt: timestamp("collateral_released_at"), // When collateral was released
  
  // Network Type (testnet4, mainnet)
  networkType: text("network_type").default("testnet4"),
});

export const loanOffers = pgTable("loan_offers", {
  id: serial("id").primaryKey(),
  loanId: integer("loan_id").notNull(),
  lenderId: integer("lender_id").notNull(),
  amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),
  interestRate: decimal("interest_rate", { precision: 5, scale: 2 }).notNull(),
  status: text("status").notNull().default("pending"), // pending, accepted, rejected
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const loanDocuments = pgTable("loan_documents", {
  id: serial("id").primaryKey(),
  loanId: integer("loan_id").notNull(),
  uploadedBy: integer("uploaded_by").notNull(),
  uploaderRole: text("uploader_role").notNull(), // 'borrower' or 'lender'
  fileName: text("file_name").notNull(),
  fileType: text("file_type").notNull(), // 'pdf', 'png', 'jpg'
  fileSize: integer("file_size").notNull(),
  objectPath: text("object_path").notNull(), // Path in object storage
  description: text("description"), // Optional description (e.g., "Bank transfer proof")
  uploadedAt: timestamp("uploaded_at").notNull().defaultNow(),
});

export const insertLoanDocumentSchema = createInsertSchema(loanDocuments).omit({
  id: true,
  uploadedAt: true,
});

export type InsertLoanDocument = z.infer<typeof insertLoanDocumentSchema>;
export type LoanDocument = typeof loanDocuments.$inferSelect;

export const userAchievements = pgTable("user_achievements", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  achievementId: text("achievement_id").notNull(),
  unlockedAt: timestamp("unlocked_at").notNull().defaultNow(),
  progress: integer("progress").notNull().default(0),
  blockchainTxHash: text("blockchain_tx_hash"),
  blockHeight: integer("block_height"),
  blockchainTimestamp: timestamp("blockchain_timestamp"),
});

// WASM Escrow Coordination Tables (Firefish Integration)
export const escrowSessions = pgTable("escrow_sessions", {
  id: serial("id").primaryKey(),
  sessionId: text("session_id").notNull().unique(), // UUID from frontend
  loanId: integer("loan_id").notNull(),
  
  // Escrow Address Info (from WASM)
  escrowAddress: text("escrow_address").notNull(),
  witnessScript: text("witness_script").notNull(),
  scriptHash: text("script_hash").notNull(),
  
  // 3-of-3 Multisig Public Keys (Bitcoin-blind lender design)
  // NOTE: lenderPubkey is platform-generated (lender is Bitcoin-blind)
  borrowerPubkey: text("borrower_pubkey").notNull(),
  lenderPubkey: text("lender_pubkey"), // Platform-operated key for lender's escrow position
  platformPubkey: text("platform_pubkey").notNull(),
  
  // Encrypted lender key private key for platform signing
  lenderPrivateKeyEncrypted: text("lender_private_key_encrypted"),
  
  // State from Firefish WASM
  wasmState: text("wasm_state"), // Serialized borrower state from WASM
  currentState: text("current_state").notNull().default("initialized"), // initialized, waiting_funding, funded, signatures_exchanged, active, completed
  
  // Transaction Hashes (pre-signed tx identifiers)
  repaymentTxHash: text("repayment_tx_hash"),
  defaultTxHash: text("default_tx_hash"),
  liquidationTxHash: text("liquidation_tx_hash"),
  recoveryTxHash: text("recovery_tx_hash"),
  
  // Blockchain Data
  fundingTxid: text("funding_txid"),
  fundingVout: integer("funding_vout"),
  fundedAmountSats: integer("funded_amount_sats"),
  
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const signatureExchanges = pgTable("signature_exchanges", {
  id: serial("id").primaryKey(),
  escrowSessionId: text("escrow_session_id").notNull(),
  
  // Signature Data (base64 encoded)
  senderRole: text("sender_role").notNull(), // "ted_o" or "ted_p" (platform oracles)
  signatureType: text("signature_type").notNull(), // "repayment", "default", "liquidation"
  signatureData: text("signature_data").notNull(), // Base64 encoded signatures
  
  // Metadata
  receivedFromClient: boolean("received_from_client").notNull().default(false),
  processedAt: timestamp("processed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const escrowEvents = pgTable("escrow_events", {
  id: serial("id").primaryKey(),
  escrowSessionId: text("escrow_session_id").notNull(),
  eventType: text("event_type").notNull(), // "created", "funded", "signature_received", "completed", "defaulted"
  eventData: text("event_data"), // JSON blob with event details
  blockchainTxid: text("blockchain_txid"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Pre-signed Transactions (Firefish Ephemeral Key Model)
// Stores the signed transactions that users download and can re-upload for broadcast
export const preSignedTransactions = pgTable("pre_signed_transactions", {
  id: serial("id").primaryKey(),
  loanId: integer("loan_id").notNull(),
  
  // Party Info
  partyRole: text("party_role").notNull(), // "borrower" | "lender" | "platform"
  partyPubkey: text("party_pubkey").notNull(),
  
  // Transaction Info
  txType: text("tx_type").notNull(), // "recovery" | "cooperative_close" | "default"
  psbt: text("psbt").notNull(), // Base64 encoded PSBT
  signature: text("signature").notNull(), // Party's signature
  txHash: text("tx_hash").notNull(), // Transaction identifier
  
  // Broadcast Status
  broadcastStatus: text("broadcast_status").notNull().default("pending"), // pending, broadcasting, confirmed, failed
  broadcastTxid: text("broadcast_txid"), // Blockchain transaction ID after broadcast
  broadcastedAt: timestamp("broadcasted_at"),
  confirmedAt: timestamp("confirmed_at"),
  
  // Metadata
  validAfter: timestamp("valid_after"), // For recovery tx with timelock
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

// Canonical PSBT Templates (Security: stores authoritative template metadata)
// Used to validate submitted PSBTs against server-generated templates
export const psbtTemplates = pgTable("psbt_templates", {
  id: serial("id").primaryKey(),
  loanId: integer("loan_id").notNull(),
  txType: text("tx_type").notNull(), // "recovery" | "cooperative_close" | "default"
  
  // Canonical Transaction Data (derived from server-generated template)
  canonicalTxid: text("canonical_txid").notNull(), // Derived from PSBT
  
  // Input (escrow UTXO)
  inputTxid: text("input_txid").notNull(),
  inputVout: integer("input_vout").notNull(),
  inputValue: integer("input_value").notNull(), // Satoshis
  witnessScriptHash: text("witness_script_hash").notNull(),
  
  // Outputs (strict: no hidden outputs allowed)
  outputAddress: text("output_address").notNull(), // Single output recipient
  outputValue: integer("output_value").notNull(), // Satoshis
  
  // Fee Calculation
  feeRate: integer("fee_rate").notNull(), // sats/vbyte at template creation
  virtualSize: integer("virtual_size").notNull(), // vbytes
  fee: integer("fee").notNull(), // Calculated fee in satoshis
  
  // Original PSBT (for reference)
  psbtBase64: text("psbt_base64").notNull(),
  
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export type PsbtTemplate = typeof psbtTemplates.$inferSelect;
export type InsertPsbtTemplate = typeof psbtTemplates.$inferInsert;

export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  createdAt: true,
});

export const disputes = pgTable("disputes", {
  id: serial("id").primaryKey(),
  loanId: integer("loan_id").notNull(),
  raisedBy: integer("raised_by").notNull(), // userId of party filing dispute
  disputeType: text("dispute_type").notNull(), // "borrower_default", "lender_non_payout", "other"
  status: text("status").notNull().default("open"), // open, under_review, resolved, dismissed
  resolution: text("resolution"), // Resolution decision
  broadcastTxid: text("broadcast_txid"), // TXID of broadcast tx if dispute resulted in on-chain action
  raisedAt: timestamp("raised_at").notNull().defaultNow(),
  resolvedAt: timestamp("resolved_at"),
});

export const insertLoanSchema = createInsertSchema(loans).omit({
  id: true,
  borrowerId: true,
  lenderId: true,
  status: true,
  requestedAt: true,
  fundedAt: true,
  repaidAt: true,
  collateralBtc: true,
  ltvRatio: true,
  dueDate: true,
  escrowAddress: true,
  escrowWitnessScript: true,
  escrowScriptHash: true,
  // borrowerPubkey: true,  // REMOVED - Now accepted from frontend when creating loan
  lenderPubkey: true,
  platformPubkey: true,
  fundingTxid: true,
  fundingVout: true,
  fundedAmountSats: true,
  escrowState: true,
  escrowSessionId: true,
  fiatTransferConfirmed: true,
  borrowerConfirmedReceipt: true,
  loanStartedAt: true,
  disputeStatus: true,
  disputeResolvedAt: true,
  txRepaymentHex: true,
  txDefaultHex: true,
  txLiquidationHex: true,
  txRecoveryHex: true,
  txCancellationHex: true,
});

export const insertLoanOfferSchema = createInsertSchema(loanOffers).omit({
  id: true,
  lenderId: true,
  status: true,
  createdAt: true,
});

export const insertUserAchievementSchema = createInsertSchema(userAchievements).omit({
  id: true,
  unlockedAt: true,
});

// WASM Escrow Coordination Schemas
export const insertEscrowSessionSchema = createInsertSchema(escrowSessions).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

// Schema for client-initiated WASM state updates (RESTRICTED - only allows wasmState updates)
export const updateEscrowSessionClientSchema = z.object({
  wasmState: z.string().optional(), // Only allow clients to update their WASM state
});

// Schema for server-controlled escrow updates (blockchain-derived data)
export const updateEscrowSessionServerSchema = z.object({
  currentState: z.string().optional(),
  fundingTxid: z.string().optional(),
  fundingVout: z.number().optional(),
  fundedAmountSats: z.number().optional(),
  lenderPubkey: z.string().optional(), // Can be added when lender joins
  repaymentTxHash: z.string().optional(),
  defaultTxHash: z.string().optional(),
  liquidationTxHash: z.string().optional(),
  recoveryTxHash: z.string().optional(),
});

export const insertSignatureExchangeSchema = createInsertSchema(signatureExchanges).omit({
  id: true,
  createdAt: true,
});

export const insertEscrowEventSchema = createInsertSchema(escrowEvents).omit({
  id: true,
  createdAt: true,
});

export const insertPreSignedTransactionSchema = createInsertSchema(preSignedTransactions).omit({
  id: true,
  createdAt: true,
  broadcastStatus: true,
  broadcastedAt: true,
  confirmedAt: true,
});

export const insertDisputeSchema = createInsertSchema(disputes).omit({
  id: true,
  createdAt: true,
  resolvedAt: true,
  broadcastTxid: true,
});

// Dispute Resolution Audit Log (tracks all deterministic outcome decisions)
export const disputeAuditLogs = pgTable("dispute_audit_logs", {
  id: serial("id").primaryKey(),
  loanId: integer("loan_id").notNull(),
  disputeId: integer("dispute_id"), // Can be null if resolved without formal dispute
  
  // Decision Details
  outcome: text("outcome").notNull(), // LoanOutcome enum value
  ruleFired: text("rule_fired").notNull(), // Which rule triggered the decision
  txTypeUsed: text("tx_type_used").notNull(), // "repayment", "default", "liquidation", etc.
  
  // Evidence at time of decision
  evidenceSnapshot: text("evidence_snapshot").notNull(), // JSON blob of DisputeEvidence
  
  // Blockchain Result
  broadcastTxid: text("broadcast_txid"), // TXID if transaction was broadcast
  broadcastSuccess: boolean("broadcast_success"),
  broadcastError: text("broadcast_error"),
  
  // Admin/Trigger Info
  triggeredBy: integer("triggered_by").notNull(), // userId who triggered resolution
  triggeredByRole: text("triggered_by_role").notNull(), // "admin" or "system"
  
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const insertDisputeAuditLogSchema = createInsertSchema(disputeAuditLogs).omit({
  id: true,
  createdAt: true,
});

// ============================================================================
// DISPUTE RESOLUTION TYPES - Deterministic Outcome Engine
// ============================================================================

/**
 * FINITE SET OF DISPUTE DECISIONS
 * Admin can ONLY choose from these pre-defined outcomes.
 * Each maps to a specific pre-signed transaction template.
 */
export const DisputeDecisionEnum = z.enum([
  'BORROWER_WINS',     // Return collateral to borrower (uses txRepaymentHex/recovery)
  'LENDER_WINS',       // Send collateral to lender (uses txDefaultHex/liquidation)
  'TIMEOUT_DEFAULT',   // Follow default timeout rule (uses txLiquidationHex)
]);

export type DisputeDecision = z.infer<typeof DisputeDecisionEnum>;

/**
 * Mapping from decision to transaction field
 * This guarantees deterministic payout - admin cannot invent new addresses
 */
export const DECISION_TO_TX_FIELD: Record<DisputeDecision, keyof Loan> = {
  'BORROWER_WINS': 'txRepaymentHex',    // Cooperative close returning to borrower
  'LENDER_WINS': 'txDefaultHex',         // Default tx sending to lender
  'TIMEOUT_DEFAULT': 'txLiquidationHex', // Liquidation after timeout
};

/**
 * Human-readable labels for UI
 */
export const DECISION_LABELS: Record<DisputeDecision, { title: string; description: string; icon: string }> = {
  'BORROWER_WINS': {
    title: 'Borrower Wins',
    description: 'Return collateral to borrower address',
    icon: '✅',
  },
  'LENDER_WINS': {
    title: 'Lender Wins', 
    description: 'Send collateral to lender address',
    icon: '💰',
  },
  'TIMEOUT_DEFAULT': {
    title: 'Timeout / Default Rule',
    description: 'Apply default timeout liquidation',
    icon: '⏰',
  },
};

// API Request/Response schemas
export const resolveDisputeRequestSchema = z.object({
  decision: DisputeDecisionEnum,
  adminNotes: z.string().optional(),
});

export type ResolveDisputeRequest = z.infer<typeof resolveDisputeRequestSchema>;

export const resolveDisputeResponseSchema = z.object({
  success: z.boolean(),
  txid: z.string().optional(),
  decision: DisputeDecisionEnum.optional(),
  error: z.string().optional(),
  auditLogId: z.number().optional(),
});

export type ResolveDisputeResponse = z.infer<typeof resolveDisputeResponseSchema>;

// TypeScript Types
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type Loan = typeof loans.$inferSelect;
export type InsertLoan = z.infer<typeof insertLoanSchema>;
export type LoanOffer = typeof loanOffers.$inferSelect;
export type InsertLoanOffer = z.infer<typeof insertLoanOfferSchema>;
export type UserAchievement = typeof userAchievements.$inferSelect;
export type InsertUserAchievement = z.infer<typeof insertUserAchievementSchema>;
export type Dispute = typeof disputes.$inferSelect;
export type InsertDispute = z.infer<typeof insertDisputeSchema>;

// WASM Escrow Types
export type EscrowSession = typeof escrowSessions.$inferSelect;
export type InsertEscrowSession = z.infer<typeof insertEscrowSessionSchema>;
export type SignatureExchange = typeof signatureExchanges.$inferSelect;
export type InsertSignatureExchange = z.infer<typeof insertSignatureExchangeSchema>;
export type EscrowEvent = typeof escrowEvents.$inferSelect;
export type InsertEscrowEvent = z.infer<typeof insertEscrowEventSchema>;
export type PreSignedTransaction = typeof preSignedTransactions.$inferSelect;
export type InsertPreSignedTransaction = z.infer<typeof insertPreSignedTransactionSchema>;

// Dispute Audit Log Types
export type DisputeAuditLog = typeof disputeAuditLogs.$inferSelect;
export type InsertDisputeAuditLog = z.infer<typeof insertDisputeAuditLogSchema>;
