import { pgTable, text, serial, integer, decimal, timestamp, boolean } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  username: text("username").notNull().unique(),
  email: text("email").notNull().unique(),
  password: text("password").notNull(),
  role: text("role").notNull().default("user"), // user (can both borrow and lend)
  reputation: integer("reputation").notNull().default(0),
  completedLoans: integer("completed_loans").notNull().default(0),
  emailVerified: boolean("email_verified").notNull().default(false),
  emailVerificationToken: text("email_verification_token"),
  emailVerificationExpires: timestamp("email_verification_expires"),
  passwordResetToken: text("password_reset_token"),
  passwordResetExpires: timestamp("password_reset_expires"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const loans = pgTable("loans", {
  id: serial("id").primaryKey(),
  borrowerId: integer("borrower_id").notNull(),
  lenderId: integer("lender_id"),
  amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),
  currency: text("currency").notNull().default("USDC"),
  interestRate: decimal("interest_rate", { precision: 5, scale: 2 }).notNull(),
  termMonths: integer("term_months").notNull(),
  collateralBtc: decimal("collateral_btc", { precision: 10, scale: 8 }).notNull(),
  ltvRatio: decimal("ltv_ratio", { precision: 5, scale: 2 }).notNull(),
  purpose: text("purpose"),
  status: text("status").notNull().default("posted"), // posted, funding, initiated, active, completed, defaulted
  requestedAt: timestamp("requested_at").notNull().defaultNow(),
  fundedAt: timestamp("funded_at"),
  dueDate: timestamp("due_date"),
  repaidAt: timestamp("repaid_at"),
  
  // WASM-Generated Escrow Fields (NO PRIVATE KEYS!)
  escrowAddress: text("escrow_address"), // Generated by WASM in browser
  escrowWitnessScript: text("escrow_witness_script"), // P2WSH witness script
  escrowScriptHash: text("escrow_script_hash"),
  
  // Public Keys Only (generated by Firefish WASM)
  borrowerPubkey: text("borrower_pubkey"),
  lenderPubkey: text("lender_pubkey"),
  platformPubkey: text("platform_pubkey"),
  
  // Blockchain Transaction Tracking
  fundingTxid: text("funding_txid"), // Funding transaction ID
  fundingVout: integer("funding_vout"), // Output index
  fundedAmountSats: integer("funded_amount_sats"),
  
  // Escrow Workflow State
  escrowState: text("escrow_state").default("initialized"), // initialized, waiting_funding, funded, active, completed, defaulted
  escrowSessionId: text("escrow_session_id"), // Links to escrow_sessions table
  
  // Workflow Flags
  fiatTransferConfirmed: boolean("fiat_transfer_confirmed").default(false),
  borrowerConfirmedReceipt: boolean("borrower_confirmed_receipt").default(false),
  loanStartedAt: timestamp("loan_started_at"),
});

export const loanOffers = pgTable("loan_offers", {
  id: serial("id").primaryKey(),
  loanId: integer("loan_id").notNull(),
  lenderId: integer("lender_id").notNull(),
  amount: decimal("amount", { precision: 10, scale: 2 }).notNull(),
  interestRate: decimal("interest_rate", { precision: 5, scale: 2 }).notNull(),
  status: text("status").notNull().default("pending"), // pending, accepted, rejected
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const userAchievements = pgTable("user_achievements", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").notNull(),
  achievementId: text("achievement_id").notNull(),
  unlockedAt: timestamp("unlocked_at").notNull().defaultNow(),
  progress: integer("progress").notNull().default(0),
  blockchainTxHash: text("blockchain_tx_hash"),
  blockHeight: integer("block_height"),
  blockchainTimestamp: timestamp("blockchain_timestamp"),
});

// WASM Escrow Coordination Tables (Firefish Integration)
export const escrowSessions = pgTable("escrow_sessions", {
  id: serial("id").primaryKey(),
  sessionId: text("session_id").notNull().unique(), // UUID from frontend
  loanId: integer("loan_id").notNull(),
  
  // Escrow Address Info (from WASM)
  escrowAddress: text("escrow_address").notNull(),
  witnessScript: text("witness_script").notNull(),
  scriptHash: text("script_hash").notNull(),
  
  // Public Keys (NO PRIVATE KEYS!)
  borrowerPubkey: text("borrower_pubkey").notNull(),
  lenderPubkey: text("lender_pubkey"),
  platformPubkey: text("platform_pubkey").notNull(),
  
  // State from Firefish WASM
  wasmState: text("wasm_state"), // Serialized borrower state from WASM
  currentState: text("current_state").notNull().default("initialized"), // initialized, waiting_funding, funded, signatures_exchanged, active, completed
  
  // Transaction Hashes (pre-signed tx identifiers)
  repaymentTxHash: text("repayment_tx_hash"),
  defaultTxHash: text("default_tx_hash"),
  liquidationTxHash: text("liquidation_tx_hash"),
  recoveryTxHash: text("recovery_tx_hash"),
  
  // Blockchain Data
  fundingTxid: text("funding_txid"),
  fundingVout: integer("funding_vout"),
  fundedAmountSats: integer("funded_amount_sats"),
  
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

export const signatureExchanges = pgTable("signature_exchanges", {
  id: serial("id").primaryKey(),
  escrowSessionId: text("escrow_session_id").notNull(),
  
  // Signature Data (base64 encoded)
  senderRole: text("sender_role").notNull(), // "ted_o" or "ted_p" (platform oracles)
  signatureType: text("signature_type").notNull(), // "repayment", "default", "liquidation"
  signatureData: text("signature_data").notNull(), // Base64 encoded signatures
  
  // Metadata
  receivedFromClient: boolean("received_from_client").notNull().default(false),
  processedAt: timestamp("processed_at"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

export const escrowEvents = pgTable("escrow_events", {
  id: serial("id").primaryKey(),
  escrowSessionId: text("escrow_session_id").notNull(),
  eventType: text("event_type").notNull(), // "created", "funded", "signature_received", "completed", "defaulted"
  eventData: text("event_data"), // JSON blob with event details
  blockchainTxid: text("blockchain_txid"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});



export const insertUserSchema = createInsertSchema(users).omit({
  id: true,
  createdAt: true,
});

export const insertLoanSchema = createInsertSchema(loans).omit({
  id: true,
  borrowerId: true,
  lenderId: true,
  status: true,
  requestedAt: true,
  fundedAt: true,
  repaidAt: true,
  collateralBtc: true,
  ltvRatio: true,
  dueDate: true,
  escrowAddress: true,
  escrowRedeemScript: true,
  borrowerPubkey: true,
  lenderPubkey: true,
  platformPubkey: true,
  escrowTxHash: true,
  fiatTransferConfirmed: true,
  borrowerConfirmedReceipt: true,
  loanStartedAt: true,
});

export const insertLoanOfferSchema = createInsertSchema(loanOffers).omit({
  id: true,
  lenderId: true,
  status: true,
  createdAt: true,
});

export const insertUserAchievementSchema = createInsertSchema(userAchievements).omit({
  id: true,
  unlockedAt: true,
});

// WASM Escrow Coordination Schemas
export const insertEscrowSessionSchema = createInsertSchema(escrowSessions).omit({
  id: true,
  createdAt: true,
  updatedAt: true,
});

// Schema for client-initiated WASM state updates (RESTRICTED - only allows wasmState updates)
export const updateEscrowSessionClientSchema = z.object({
  wasmState: z.string().optional(), // Only allow clients to update their WASM state
});

// Schema for server-controlled escrow updates (blockchain-derived data)
export const updateEscrowSessionServerSchema = z.object({
  currentState: z.string().optional(),
  fundingTxid: z.string().optional(),
  fundingVout: z.number().optional(),
  fundedAmountSats: z.number().optional(),
  lenderPubkey: z.string().optional(), // Can be added when lender joins
  repaymentTxHash: z.string().optional(),
  defaultTxHash: z.string().optional(),
  liquidationTxHash: z.string().optional(),
  recoveryTxHash: z.string().optional(),
});

export const insertSignatureExchangeSchema = createInsertSchema(signatureExchanges).omit({
  id: true,
  createdAt: true,
});

export const insertEscrowEventSchema = createInsertSchema(escrowEvents).omit({
  id: true,
  createdAt: true,
});

// TypeScript Types
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;
export type Loan = typeof loans.$inferSelect;
export type InsertLoan = z.infer<typeof insertLoanSchema>;
export type LoanOffer = typeof loanOffers.$inferSelect;
export type InsertLoanOffer = z.infer<typeof insertLoanOfferSchema>;
export type UserAchievement = typeof userAchievements.$inferSelect;
export type InsertUserAchievement = z.infer<typeof insertUserAchievementSchema>;

// WASM Escrow Types
export type EscrowSession = typeof escrowSessions.$inferSelect;
export type InsertEscrowSession = z.infer<typeof insertEscrowSessionSchema>;
export type SignatureExchange = typeof signatureExchanges.$inferSelect;
export type InsertSignatureExchange = z.infer<typeof insertSignatureExchangeSchema>;
export type EscrowEvent = typeof escrowEvents.$inferSelect;
export type InsertEscrowEvent = z.infer<typeof insertEscrowEventSchema>;
